name: Build and Deploy Host

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Remove npm cache
        run: npm cache clean --force

      - name: Remove local node_modules + lockfile
        run: rm -rf node_modules package-lock.json

      - name: Install fresh dependencies
        run: npm install --force

      - name: Verify ui-kit entry file exists
        run: ls -la node_modules/@anthonyv449/ui-kit/dist/index.js

      - name: List package contents
        run: ls -R node_modules/@anthonyv449/ui-kit

      - name: Show package.json entry point
        run: cat node_modules/@anthonyv449/ui-kit/package.json

      - name: Build host
        run: npm run build

      - name: Copy public assets
        run: |
          mkdir -p dist/host
          cp -r host/public/* dist/host/

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name uiremotes -s dist/host -d '$web/host' --overwrite
