      - name: npm install, build, and test
        run: |
          npm install
          npm run build

      - name: Zip artifact for deployment
        run: zip -r release.zip dist

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
